services:
  backend:
    image: alokpaul2/medicoin-be
    container_name: backend
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:80
    depends_on:
      - backend
