version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173" # Adjust for your React dev server
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
